pipeline{

    agent any

    stages{
        stage('Deploy') {

            steps {

                sh '''
                oc project test-cr-jenkins-deploy-strategies
                oc start-build greeting-service --follow --wait
                '''
            }
        }
    }
}
